server:
  servlet:
    session:
      timeout: 60m
  error:
    include-binding-errors: always
    include-message: always
    whitelabel:
      enabled: false
    path: /error
spring:
  datasource:
    hikari:
      maximum-pool-size: 30
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/indish?serverTimezone=UTC&useLegacyDatetimeCode=false

    ## Hibernate Properties
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    ## Hibernate Properties

  mvc:
    throw-exception-if-no-handler-found: true

  web:
    resources:
      add-mappings: false
app:
  jwt-secret: qFK7ecoef5w1n393ndjny507cop66kl
  jwt-expiration-milliseconds: 10800000

  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 215MB
      file-size-threshold: 2KB

  ## File Storage Properties
file:
  upload-dir: ./uploads