server:
  error:
    include-binding-errors: always
    include-message: always
    whitelabel:
      enabled: false
  port: 8080


#The AutoConfigureTestDatabase.Replace.NONE annotation property tells Spring not to replace the database with an embedded database.
#If we didn’t do this, Spring wouldn’t be using the MySQL data source and would try to autoconfigure an embedded database instead.
spring:
  test:
    database:
      replace: none
  mail:
    host: smtp.gmail.com
    port: 587
    username: <YOUR_EMAIL>
    password: <YOUR_PASSWORD>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
    protocol: smtp

  datasource:
    hikari:
      maximum-pool-size: 30
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/indish?serverTimezone=UTC&useLegacyDatetimeCode=false

    ## Hibernate Properties
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    ## Hibernate Properties

  mvc:
    throw-exception-if-no-handler-found: true

  web:
    resources:
      add-mappings: false
app:
  jwt-secret: qFK7ecoef5w1n393ndjny507cop66kl
  jwt-expiration-milliseconds: 10800000

  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 215MB
      file-size-threshold: 2KB

  ## File Storage Properties
file:
  upload-dir: ./uploads