server:
  error:
    include-binding-errors: always
    include-message: always
    whitelabel:
      enabled: false
spring:
  datasource:
    hikari:
      maximum-pool-size: 30
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/indish

    ## Hibernate Properties
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    ## Hibernate Properties

  mvc:
    throw-exception-if-no-handler-found: true
    pathmatch:
      matching-strategy: ant_path_matcher
  web:
    resources:
      add-mappings: false
